version: '3.8'

services:
  jsrobot-merc:
    build: .
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jsrobot-merc.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.jsrobot-merc.tls=true"
      - "traefik.http.routers.jsrobot-merc.tls.certresolver=letsencrypt"
      - "traefik.http.services.jsrobot-merc.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
